# Generated by Django 4.1.1 on 2022-10-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advfavorite',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='advfavorite',
            name='user',
        ),
        migrations.AddField(
            model_name='advfavorite',
            name='advertisements',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='advertisements.advertisement'),
        ),
    ]
