# Generated by Django 4.1.1 on 2022-10-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0003_remove_advfavorite_advertisement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advfavorite',
            name='fv_users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fv_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
