# Generated by Django 4.1.1 on 2022-10-18 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0005_alter_advertisement_id_alter_advfavorite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advfavorite',
            name='advertisements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='advertisements.advertisement'),
        ),
        migrations.AlterField(
            model_name='advfavorite',
            name='fv_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fv_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
